{application,bibi,
             [{description,[]},
              {vsn,"1.1.4"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{bibi_app,[]}},
              {env,[]},
              {modules,[bi_name,bi_queue,bi_room,bi_server,bibi_app,bibi_sup,
                        ws_handler]}]}.
