{application,bibi,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{bibi_app,[]}},
              {env,[]},
              {modules,[bi_name,bi_queue,bi_room,bibi_app,bibi_sup,
                        ws_handler]}]}.
